trigger:
  branches:
    include:
      - main

pool: 'fedeWSL'

steps:
  - task: Docker@2
    displayName: 'Build and Push Docker image'
    inputs:
      containerRegistry: 'JFrog Registry'
      repository: 'https://a0muixhnkluno.jfrog.io/artifactory/prova2/'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        tag1
        tag2
  - task: JFrogDocker@1
    displayName: 'Push Docker image to JFrog Artifactory'
    inputs:
      command: 'Push'
      artifactoryConnection: 'prova2'
      imageName: 'prova2/nginx:latest'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      threads: '3'
      skipLogin: false

  - task: JFrogDocker@1
    displayName: 'Pull Docker image from JFrog Artifactory'
    inputs:
      command: 'Pull'
      artifactoryConnection: 'prova2'
      imageName: 'prova2/nginx:latest'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
