trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JFrogDocker@1
    displayName: 'Push Docker image to JFrog Artifactory'
    inputs:
      command: 'Push'
      artifactoryConnection: 'prova2'
      imageName: 'prova2/image-name:tag'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      threads: '3'
      skipLogin: false

  - task: JFrogDocker@1
    displayName: 'Pull Docker image from JFrog Artifactory'
    inputs:
      command: 'Pull'
      artifactoryConnection: 'prova2'
      imageName: 'prova2/image-name:tag'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      projectKey: 'prova2'
      skipLogin: false
